### ISSUE TITLE
If user is logged-in in more than 1 computer, license is counted for every used computer

### ISSUE THREAD

**Issue by Phorms** [FutureProcessing/glpi-fpsoftware#5]
See (german) screenshot for details:
![2015-12-17_16h49_42](https://cloud.githubusercontent.com/assets/14980311/11874150/83148d66-a4de-11e5-9605-cbf4c760f792.png)

**Comment by prybak** [comment]
We will be fixing that.

**Comment by prybak** [comment]
Please download latest sources of fp-software plugin and after upgrade go to plugins settings page (Setup -> Plugins). Click "FP Software" and select desired option - "Calculate licenses number per user instead of per computer". It is not the best name for this option, we will change it. Please let me know if that resolved your issue.

**Comment by prybak** [comment]
We've also proposed modification of GLPI source code to display proper number of used/assigned licenses. Please take a look at readme.

**Comment by prybak** [comment]
Did the latest update resolve your issue?

**Comment by prybak** [comment]
No response, this was tested internally.
